function renderMultiplication(){
  setLast('multiplication');
  app.innerHTML=lessonShell('Perkalian Bilangan Bulat','Mulai dari situasi sehari-hari, susun kelompok, lalu temukan pola tandanya.',`<div class="section"><p class="eyebrow">Contoh sehari-hari</p><h2>🎮 Kehilangan poin dalam 3 ronde</h2><div class="story-strip"><span class="story-icon">🎮</span><div><b>Dalam setiap ronde, skor Dimas berkurang 2 poin. Ia bermain 3 ronde.</b><small>3 × (−2) berarti tiga kelompok perubahan −2.</small></div></div><div id="mulSource" class="object-bank"><span class="score-token" draggable="true">−2</span><span class="score-token" draggable="true">−2</span><span class="score-token" draggable="true">−2</span></div><p class="instruction">Seret setiap perubahan −2 ke satu kotak ronde.</p><div id="mulGroups" class="pictorial-groups">${[1,2,3].map(i=>`<div class="picture-group drop-group" data-slot="${i}"><b>Ronde ${i}</b><div class="slot-content"></div></div>`).join('')}</div><div id="mulStoryFeedback" class="feedback">Terisi 0 dari 3 ronde.</div></div><div class="section" id="mulPatternSection" style="display:none"><p class="eyebrow">Temukan pola</p><h2>Apa yang terjadi pada tandanya?</h2><p>Jika satu faktor turun satu langkah, amati perubahan hasilnya.</p><div class="pattern-row"><b>2 × (−2)</b><span>=</span><b>−4</b></div><div class="pattern-row"><b>1 × (−2)</b><span>=</span><b>−2</b></div><div class="pattern-row"><b>0 × (−2)</b><span>=</span><b>0</b></div><div class="pattern-row"><b>(−1) × (−2)</b><span>=</span><div>${choices([-2,2,-1,1],2)}</div></div><div id="multiplyConclusion"></div></div>`);
  setupTokenDrag();
  function setupTokenDrag(){
    let dragged=null,filled=0;
    document.querySelectorAll('.score-token').forEach(t=>t.addEventListener('dragstart',e=>{dragged=t;e.dataTransfer.setData('text/plain','-2')}));
    document.querySelectorAll('.drop-group').forEach(g=>{g.addEventListener('dragover',e=>{e.preventDefault();g.classList.add('drag-over')});g.addEventListener('dragleave',()=>g.classList.remove('drag-over'));g.addEventListener('drop',e=>{e.preventDefault();g.classList.remove('drag-over');place(g)});g.addEventListener('click',()=>{const t=[...document.querySelectorAll('.score-token')].find(x=>!x.classList.contains('used'));if(t){dragged=t;place(g)}})});
    function place(g){
      if(!dragged||g.classList.contains('filled')||dragged.classList.contains('used'))return;
      g.classList.add('filled');g.querySelector('.slot-content').innerHTML='<span class="score-token placed">−2</span><div class="tiny-cards">'+cards(0,2)+'</div>';dragged.classList.add('used');filled++;mulStoryFeedback.innerHTML=`Terisi <b>${filled} dari 3</b> ronde.${filled===3?' Total perubahan: (−2)+(−2)+(−2)=<b>−6</b>.':''}`;dragged=null;
      if(filled===3){mulPatternSection.style.display='block';mulPatternSection.scrollIntoView({behavior:'smooth',block:'start'});wireChoices(2,()=>{document.getElementById('multiplyConclusion').innerHTML='<div class="result-sentence pop"><span class="result-check">✓</span><div><b>Benar!</b><p>Jadi hasil dari <strong>(−1) × (−2)</strong> adalah <strong>+2</strong>.</p><small>Tanda sama menghasilkan positif. Tanda berbeda menghasilkan negatif.</small></div></div>';startTopicPractice({title:'Latihan Perkalian',subtitle:'Kerjakan contoh soal acak dari situasi sehari-hari sebelum melanjutkan ke pembagian.',count:5,makeQuestion:multiplicationQuestion,onComplete:()=>{complete('multiplication');go('division')}})})}
    }
  }
}
